language: ruby
rvm:
  - "2.4.0"
gemfile: Gemfile
script: bundle exec ruby test_app.rb
notifications:
  recipients:
    - scott.sproule@estormtech.com
  email:
    on_success: change
    on_failure: always

