# fly.toml file generated for ficonab-com on 2022-08-13T22:46:36-07:00

app = "ficonab-com"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
# [processes]
#   web = "bundle exec falcon serve --count 3  -b http://[::]:8080"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/ruby"]
  [build.args]
    RUBY_VERSION = "3.1.1"

[deploy]

[env]
  PORT = "8080"
  # orig SERVER_COMMAND = "bundle exec puma -C config/puma.rb"
  SERVER_COMMAND = "bundle exec falcon serve --count 3  -b http://[::]:8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
